name: Build My Demo App
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build-ios:
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        - macos-version: macos-14
          xcode-version: 15.4
          destination: "name=iPhone 15 Pro Max"
    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Build for iOS Simulator
      run:  |
        set -o pipefail && \
        xcodebuild \
          ONLY_ACTIVE_ARCH=NO \
          ARCHS_STANDARD="x86_64 arm64" \
          build \
          -workspace "My Demo App.xcworkspace" \
          -scheme "My Demo App" \
          -sdk iphonesimulator \
          -destination "${{ matrix.destination }}" \
          -configuration Release \
          -derivedDataPath build | xcpretty
