name: Build My Demo App
on: 
  push:
  pull_request:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build-ios:
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
        - macos-version: macos-11
          xcode-version: 12.5.1
          destination: "name=iPhone 11 Pro Max"
    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Build for iOS Simulator
      run:  |
        set -o pipefail && \
        xcodebuild \
          ONLY_ACTIVE_ARCH=NO \
          ARCHS_STANDARD="i386 x86_64" \
          build \
          -workspace "My Demo App.xcworkspace" \
          -scheme "My Demo App" \
          -sdk iphonesimulator \
          -destination "${{ matrix.destination }}" \
          -configuration Release \
          -derivedDataPath build | xcpretty
