name: Run Tests for My Demo App
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  run-tests:
    runs-on: macos-14
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
        - xcode-version: 15.4
          destination: "name=iPhone 15 Pro Max"
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Run Tests
      run: |
        xcodebuild \
          test \
          -workspace "My Demo App.xcworkspace" \
          -scheme "My Demo App" \
          -skip-testing MyDemoAppUITests/FailedTests \
          -destination "${{ matrix.destination }}" | xcpretty

  run-tests-on-saucelabs:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: gem install xcpretty
      - name: Select XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4
      - name: Build for testing
        run:  |
          set -o pipefail && \
          xcodebuild \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build-for-testing \
            -workspace "My Demo App.xcworkspace" \
            -scheme "My Demo App" \
            -destination "generic/platform=ios" \
            -configuration Release \
            -derivedDataPath build | xcpretty
      - name: Test against Sauce Labs
        uses: saucelabs/saucectl-run-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}        
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
