name: Run Tests for My Demo App
on: 
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  run-tests:
    runs-on: macos-11
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
        - xcode-version: 12.5
          destination: "name=iPhone 11 Pro Max"
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Run Tests
      run: |
        xcodebuild \
          test \
          -workspace "My Demo App.xcworkspace" \
          -scheme "My Demo App" \
          -destination "${{ matrix.destination }}" | xcpretty

  run-tests-on-saucelabs:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: gem install xcpretty
      - name: Build for testing
        run:  |
          set -o pipefail && \
          xcodebuild \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
            build-for-testing \
            -workspace "My Demo App.xcworkspace" \
            -scheme "My Demo App" \
            -sdk iphoneos \
            -destination "generic/platform=ios" \
            -configuration Release \
            -derivedDataPath build | xcpretty
      - name: Test against Sauce Labs
        uses: saucelabs/saucectl-run-action@v1
        with:
          sauce-username: ${{ secrets.SAUCE_USERNAME }}
          sauce-access-key: ${{ secrets.SAUCE_ACCESS_KEY }}
